import type { Metadata } from "next";
import { Six_Caps } from "next/font/google";
import "./globals.css";

const sixCaps = Six_Caps({
  variable: "--font-six-caps",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sixCaps.variable}`}>
        {children}
        <footer>
          <h1>bla bla</h1>
        </footer>
      </body>
    </html>
  );
}
